/* Generated by Frama-C */
void bubbleinnerloop(int *a, int n)
{
  int j = 0;
  while (1) {
    /*@ assert rte: signed_overflow: -2147483648 ≤ n - 1; */
    if (! (j < n - 1)) break;
    /*@ assert rte: mem_access: \valid_read(a + j); */
    /*@ assert rte: signed_overflow: j + 1 ≤ 2147483647; */
    /*@ assert rte: mem_access: \valid_read(a + (int)(j + 1)); */
    if (*(a + j) > *(a + (j + 1))) {
      /*@ assert rte: mem_access: \valid_read(a + j); */
      int temp = *(a + j);
      /*@ assert rte: mem_access: \valid(a + j); */
      /*@ assert rte: signed_overflow: j + 1 ≤ 2147483647; */
      /*@ assert rte: mem_access: \valid_read(a + (int)(j + 1)); */
      *(a + j) = *(a + (j + 1));
      /*@ assert rte: mem_access: \valid(a + (int)(j + 1)); */
      /*@ assert rte: signed_overflow: j + 1 ≤ 2147483647; */
      *(a + (j + 1)) = temp;
    }
    /*@ assert rte: signed_overflow: j + 1 ≤ 2147483647; */
    j ++;
  }
  return;
}


