/* Generated by Frama-C */
int countSameConsecutive(int N, int *x)
{
  int best = 0;
  int i = 0;
  while (i < N) {
    /*@ assert rte: signed_overflow: i + 1 ≤ 2147483647; */
    int j = i + 1;
    while (1) {
      if (j < N) {
        /*@ assert rte: mem_access: \valid_read(x + j); */
        /*@ assert rte: mem_access: \valid_read(x + i); */
        if (! (*(x + j) == *(x + i))) break;
      }
      else break;
      /*@ assert rte: signed_overflow: j + 1 ≤ 2147483647; */
      j ++;
    }
    /*@ assert rte: signed_overflow: -2147483648 ≤ j - i; */
    /*@ assert rte: signed_overflow: j - i ≤ 2147483647; */
    if (j - i > best) 
      /*@ assert rte: signed_overflow: -2147483648 ≤ j - i; */
      /*@ assert rte: signed_overflow: j - i ≤ 2147483647; */
      best = j - i;
    i = j;
  }
  return best;
}


