/* Generated by Frama-C */
int d(char c)
{
  int tmp;
  if ('0' <= (int)c) 
    if ((int)c <= '9') 
      /*@ assert rte: signed_overflow: -2147483648 ≤ (int)c - (int)'0'; */
      tmp = (int)c - '0';
    else tmp = -1;
  else tmp = -1;
  return tmp;
}


