/* Generated by Frama-C */
extern int ( /* missing proto */ d)(int x_0);

extern int ( /* missing proto */ e)(int x_0);

int de(int i)
{
  int tmp_0;
  int tmp;
  tmp = e(i);
  tmp_0 = d(tmp);
  return tmp_0;
}


