/* Generated by Frama-C */
extern int ( /* missing proto */ d)(int x_0);

extern int ( /* missing proto */ e)(int x_0);

int ded(char c)
{
  int tmp_1;
  int tmp_0;
  int tmp;
  tmp = d((int)c);
  tmp_0 = e(tmp);
  tmp_1 = d(tmp_0);
  return tmp_1;
}


