/* Generated by Frama-C */
int eq_VC(char *a1, char *a2, int n1, int n2)
{
  int __retres;
  if (n1 != n2) {
    __retres = 0;
    goto return_label;
  }
  {
    int i = 0;
    while (i < n1) {
      /*@ assert rte: mem_access: \valid_read(a1 + i); */
      /*@ assert rte: mem_access: \valid_read(a2 + i); */
      if ((int)*(a1 + i) != (int)*(a2 + i)) {
        __retres = 0;
        goto return_label;
      }
      /*@ assert rte: signed_overflow: i + 1 ≤ 2147483647; */
      i ++;
    }
  }
  __retres = 1;
  return_label: return __retres;
}


