/* Generated by Frama-C */
#include "stddef.h"
#include "stdio.h"
enum type1 {
    scalene = 0,
    isoscele = 1,
    equilateral = 2
};
enum type2 {
    right = 0,
    acute = 1,
    obtuse = 2
};
enum type1 func1(int a, int b, int c)
{
  enum type1 __retres;
  if (a == b) {
    if (b == c) {
      __retres = equilateral;
      goto return_label;
    }
    else goto _LAND;
  }
  else {
    _LAND: ;
    if (a == b) {
      __retres = isoscele;
      goto return_label;
    }
    else 
      if (b == c) {
        __retres = isoscele;
        goto return_label;
      }
      else 
        if (c == a) {
          __retres = isoscele;
          goto return_label;
        }
        else {
          __retres = scalene;
          goto return_label;
        }
  }
  return_label: return __retres;
}

enum type2 func2(int a, int b, int c)
{
  enum type2 __retres;
  /*@ assert rte: signed_overflow: -2147483648 ≤ a * a; */
  /*@ assert rte: signed_overflow: a * a ≤ 2147483647; */
  /*@ assert rte: signed_overflow: -2147483648 ≤ b * b; */
  /*@ assert rte: signed_overflow: b * b ≤ 2147483647; */
  /*@ assert rte: signed_overflow: -2147483648 ≤ c * c; */
  /*@ assert rte: signed_overflow: c * c ≤ 2147483647; */
  /*@ assert
      rte: signed_overflow: -2147483648 ≤ (int)(b * b) + (int)(c * c);
  */
  /*@ assert
      rte: signed_overflow: (int)(b * b) + (int)(c * c) ≤ 2147483647;
  */
  if (a * a == b * b + c * c) {
    __retres = right;
    goto return_label;
  }
  else 
    /*@ assert rte: signed_overflow: -2147483648 ≤ a * a; */
    /*@ assert rte: signed_overflow: a * a ≤ 2147483647; */
    /*@ assert rte: signed_overflow: -2147483648 ≤ b * b; */
    /*@ assert rte: signed_overflow: b * b ≤ 2147483647; */
    /*@ assert rte: signed_overflow: -2147483648 ≤ c * c; */
    /*@ assert rte: signed_overflow: c * c ≤ 2147483647; */
    /*@ assert
        rte: signed_overflow: -2147483648 ≤ (int)(b * b) + (int)(c * c);
    */
    /*@ assert
        rte: signed_overflow: (int)(b * b) + (int)(c * c) ≤ 2147483647;
    */
    if (a * a < b * b + c * c) {
      __retres = acute;
      goto return_label;
    }
    else {
      __retres = obtuse;
      goto return_label;
    }
  return_label: return __retres;
}


