/* Generated by Frama-C */
void inswap(int *x0, int x1, int x2)
{
  /*@ assert rte: mem_access: \valid_read(x0 + x1); */
  int x4 = *(x0 + x1);
  /*@ assert rte: mem_access: \valid_read(x0 + x2); */
  int x5 = *(x0 + x2);
  /*@ assert rte: mem_access: \valid(x0 + x1); */
  *(x0 + x1) = x5;
  /*@ assert rte: mem_access: \valid(x0 + x2); */
  *(x0 + x2) = x4;
  return;
}

void insort(int *x25, int x26)
{
  int x29 = x26;
  while (1) {
    int x30 = x29;
    int x31 = x30 > 1;
    if (! x31) break;
    int x33 = 0;
    int x34 = x29;
    {
      int x36 = 0;
      while (x36 < x34) {
        {
          /*@ assert rte: mem_access: \valid_read(x25 + x36); */
          int x37 = *(x25 + x36);
          int x38 = x33;
          /*@ assert rte: mem_access: \valid_read(x25 + x38); */
          int x39 = *(x25 + x38);
          int x40 = x37 >= x39;
          if (x40) x33 = x36;
        }
        /*@ assert rte: signed_overflow: x36 + 1 ≤ 2147483647; */
        x36 ++;
      }
    }
    int x96 = x33;
    /*@ assert rte: signed_overflow: -2147483648 ≤ x34 - 1; */
    int x95 = x34 - 1;
    inswap(x25,x95,x96);
    x29 = x95;
  }
  return;
}


