/* Generated by Frama-C */
int is_sorted(int *a, int n)
{
  int __retres;
  {
    int i = 1;
    while (i < n) {
      /*@ assert rte: signed_overflow: -2147483648 ≤ i - 1; */
      /*@ assert rte: mem_access: \valid_read(a + (int)(i - 1)); */
      /*@ assert rte: mem_access: \valid_read(a + i); */
      if (*(a + (i - 1)) > *(a + i)) {
        __retres = 0;
        goto return_label;
      }
      /*@ assert rte: signed_overflow: i + 1 ≤ 2147483647; */
      i ++;
    }
  }
  __retres = 1;
  return_label: return __retres;
}


