/* Generated by Frama-C */
int matcher_ab(char *x0)
{
  int x7;
  int x17;
  int tmp;
  /*@ assert rte: mem_access: \valid_read(x0 + 0); */
  char x2 = *(x0 + 0);
  int x3 = (int)x2 == '\000';
  if (x3) x7 = 0;
  else {
    int x6;
    int x4 = (int)x2 == 'a';
    if (x4) x6 = 0; else x6 = 0;
    x7 = x6;
  }
  if (x3) x17 = 0;
  else {
    int x16;
    int x4_0 = (int)x2 == 'a';
    if (x4_0) {
      int x15;
      char *x5 = x0 + 1;
      /*@ assert rte: mem_access: \valid_read(x5 + 0); */
      char x8 = *(x5 + 0);
      int x9 = (int)x8 == '\000';
      if (x9) x15 = 0;
      else {
        int x14;
        int x10 = (int)x8 == 'b';
        if (x10) {
          char *x11 = x5 + 1;
          /*@ assert rte: mem_access: \valid_read(x11 + 0); */
          char x12 = *(x11 + 0);
          int x13 = (int)x12 == '\000';
          x14 = x13;
        }
        else x14 = 0;
        x15 = x14;
      }
      x16 = x15;
    }
    else x16 = 0;
    x17 = x16;
  }
  if (x7) tmp = 1;
  else 
    if (x17) tmp = 1; else tmp = 0;
  int x18 = tmp;
  return x18;
}


