/* Generated by Frama-C */
int matcher_a_or_b(char *x0)
{
  int x9;
  int x12;
  int tmp;
  /*@ assert rte: mem_access: \valid_read(x0 + 0); */
  char x2 = *(x0 + 0);
  int x3 = (int)x2 == '\000';
  if (x3) x9 = 0;
  else {
    int x8;
    int x4 = (int)x2 == 'a';
    if (x4) {
      char *x5 = x0 + 1;
      /*@ assert rte: mem_access: \valid_read(x5 + 0); */
      char x6 = *(x5 + 0);
      int x7 = (int)x6 == '\000';
      x8 = x7;
    }
    else x8 = 0;
    x9 = x8;
  }
  if (x3) x12 = 0;
  else {
    int x11;
    int x10 = (int)x2 == 'b';
    if (x10) {
      char *x5_0 = x0 + 1;
      /*@ assert rte: mem_access: \valid_read(x5_0 + 0); */
      char x6_0 = *(x5_0 + 0);
      int x7_0 = (int)x6_0 == '\000';
      x11 = x7_0;
    }
    else x11 = 0;
    x12 = x11;
  }
  if (x9) tmp = 1;
  else 
    if (x12) tmp = 1; else tmp = 0;
  int x13 = tmp;
  return x13;
}


