/* Generated by Frama-C */
int max_ptr(int *a, int *b)
{
  int tmp;
  /*@ assert rte: mem_access: \valid_read(a); */
  /*@ assert rte: mem_access: \valid_read(b); */
  if (*a > *b) 
    /*@ assert rte: mem_access: \valid_read(a); */
    tmp = *a;
  else 
    /*@ assert rte: mem_access: \valid_read(b); */
    tmp = *b;
  return tmp;
}

extern int h;

int main(void)
{
  int __retres;
  h = 42;
  int a = 24;
  int b = 42;
  int x = max_ptr(& a,& b);
  __retres = 0;
  return __retres;
}


