/* Generated by Frama-C */
extern int ( /* missing proto */ pick_index)(int x_0);

int pick_element(int *p, int n)
{
  int __retres;
  int i = pick_index(n);
  /*@ assert rte: mem_access: \valid_read(p + i); */
  __retres = *(p + i);
  return __retres;
}


