/* Generated by Frama-C */
int alphabet_letter(char c)
{
  int __retres;
  if ('a' <= (int)c) {
    if ((int)c <= 'z') {
      __retres = 1;
      goto return_label;
    }
    else goto _LAND;
  }
  else {
    _LAND: ;
    if ('A' <= (int)c) 
      if ((int)c <= 'Z') {
        __retres = 1;
        goto return_label;
      }
      else {
        __retres = 0;
        goto return_label;
      }
    else {
      __retres = 0;
      goto return_label;
    }
  }
  return_label: return __retres;
}


