/* Generated by Frama-C */
void array_copy(int *src, int *dst, int n)
{
  if (src < dst) {
    /*@ assert rte: signed_overflow: -2147483648 ≤ n - 1; */
    int i = n - 1;
    while (-1 < i) {
      /*@ assert rte: mem_access: \valid(dst + i); */
      /*@ assert rte: mem_access: \valid_read(src + i); */
      *(dst + i) = *(src + i);
      /*@ assert rte: signed_overflow: -2147483648 ≤ i - 1; */
      i --;
    }
  }
  else {
    int i_0 = 0;
    while (i_0 < n) {
      /*@ assert rte: mem_access: \valid(dst + i_0); */
      /*@ assert rte: mem_access: \valid_read(src + i_0); */
      *(dst + i_0) = *(src + i_0);
      /*@ assert rte: signed_overflow: i_0 + 1 ≤ 2147483647; */
      i_0 ++;
    }
  }
  return;
}


