/* Generated by Frama-C */
int clamp(int v, int min, int max)
{
  int tmp;
  int tmp_0;
  if (v > min) tmp = v; else tmp = min;
  int low = tmp;
  if (low < max) tmp_0 = low; else tmp_0 = max;
  return tmp_0;
}


