#!/bin/bash

files=(
OutAndIn_rte.c
OutAndIn_1_rte.c
OutAndIn_2_rte.c
OutAndIn_test_rte.c
alphabet_letter_rte.c
alphabet_letter_1_rte.c
alphabet_letter_2_rte.c
array_copy_rte.c
array_copy_1_rte.c
array_copy_2_rte.c
bubbleinnerloop_rte.c
bubbleinnerloop_1_rte.c
bubbleinnerloop_2_rte.c
clamp_rte.c
clamp_1_rte.c
clamp_2_rte.c
countSameConsecutive_rte.c
countSameConsecutive_1_rte.c
countSameConsecutive_2_rte.c
d_rte.c
d_1_rte.c
d_2_rte.c
d_3_rte.c
d_4_rte.c
d_5_rte.c
de_rte.c
de_1_rte.c
ded_rte.c
ded_1_rte.c
dfa_rte.c
dfa_1_rte.c
dfa_2_rte.c
dfa_3_rte.c
dfa_4_rte.c
dfa_5_rte.c
dfa_spec_aab0_rte.c
dfa_spec_aab0_1_rte.c
dfa_spec_aab0_2_rte.c
dfa_spec_aab0_3_rte.c
dfa_spec_aab0_4_rte.c
dfa_spec_aab1_rte.c
dfa_spec_aab1_1_rte.c
dfa_spec_aab1_1_1_rte.c
dfa_spec_aab1_1_2_rte.c
dfa_spec_aab1_1_3_rte.c
dfa_spec_aab1_1_4_rte.c
dfa_spec_aab1_1_5_rte.c
dfa_spec_aab1_1_6_rte.c
dfa_spec_aab1_2_rte.c
dfa_spec_aab1_3_rte.c
dfa_spec_aab1_4_rte.c
dfa_spec_aab1_5_rte.c
dfa_spec_aab1_6_rte.c
dfa_spec_aab1_7_rte.c
dfa_spec_aab1_8_rte.c
dfa_spec_aab1_9_rte.c
distance_rte.c
distance_1_rte.c
distance_2_rte.c
e_rte.c
e_1_rte.c
e_2_rte.c
e_3_rte.c
ed_rte.c
ed_1_rte.c
ede_rte.c
ede_1_rte.c
eq_VC_rte.c
eq_VC_1_rte.c
eq_VC_2_rte.c
eq_vec_Int_rte.c
eq_vec_Int_1_rte.c
eq_vec_Int_2_rte.c
extracted_1043_rte.c
extracted_1080_rte.c
extracted_1113_rte.c
extracted_1164_rte.c
extracted_1211_rte.c
extracted_129_rte.c
extracted_136_rte.c
extracted_190_rte.c
extracted_195_rte.c
extracted_204_rte.c
extracted_213_rte.c
extracted_220_rte.c
extracted_228_rte.c
extracted_233_rte.c
extracted_234_rte.c
extracted_236_rte.c
extracted_238_rte.c
extracted_239_rte.c
extracted_241_rte.c
extracted_244_rte.c
extracted_250_rte.c
extracted_264_rte.c
extracted_267_rte.c
extracted_272_rte.c
extracted_276_rte.c
extracted_282_rte.c
extracted_283_rte.c
extracted_290_rte.c
extracted_313_rte.c
extracted_320_rte.c
extracted_346_rte.c
extracted_350_rte.c
extracted_355_rte.c
extracted_383_rte.c
extracted_390_rte.c
extracted_454_rte.c
extracted_506_rte.c
extracted_520_rte.c
extracted_531_rte.c
extracted_538_rte.c
extracted_552_rte.c
extracted_567_rte.c
extracted_578_rte.c
extracted_592_rte.c
extracted_611_rte.c
extracted_659_rte.c
extracted_668_rte.c
extracted_669_rte.c
extracted_670_rte.c
extracted_672_rte.c
extracted_673_rte.c
extracted_674_rte.c
extracted_681_rte.c
extracted_682_rte.c
extracted_683_rte.c
extracted_729_rte.c
extracted_735_rte.c
extracted_739_rte.c
extracted_746_rte.c
extracted_749_rte.c
extracted_800_rte.c
extracted_812_rte.c
extracted_820_rte.c
extracted_871_rte.c
extracted_888_rte.c
extracted_901_rte.c
extracted_952_rte.c
extracted_974_rte.c
extracted_992_rte.c
func1_rte.c
func1_1_rte.c
func1_2_rte.c
func1_3_rte.c
func1_4_rte.c
func1_5_rte.c
func2_rte.c
func2_1_rte.c
gimmeOne_rte.c
gimmeOne_1_rte.c
gimmeOne_2_rte.c
if_rte.c
if_1_rte.c
if_2_rte.c
if_3_rte.c
index_rte.c
indexOf_rte.c
indexOf_1_rte.c
indexOf_2_rte.c
index_1_rte.c
index_2_rte.c
index_where_rte.c
inswap_rte.c
inswap_1_rte.c
inswap_2_rte.c
is_nat_rte.c
is_nat_1_rte.c
is_pos_rte.c
is_pos_1_rte.c
is_pos_2_rte.c
is_pos_3_rte.c
is_pos_4_rte.c
is_pos_5_rte.c
is_pos_6_rte.c
is_pos_7_rte.c
is_pos_8_rte.c
is_sorted_rte.c
is_sorted_1_rte.c
is_sorted_2_rte.c
lemma01_rte.c
lemma01_1_rte.c
lemma01_2_rte.c
lemma01_3_rte.c
lemma01_4_rte.c
lemma01_5_rte.c
lemma01_6_rte.c
lemma01_7_rte.c
lemma01_8_rte.c
lemma11_rte.c
lemma11_1_rte.c
lemma11_2_rte.c
lemma11_3_rte.c
lemma11_4_rte.c
lemma11_5_rte.c
lemma11_6_rte.c
lemma12_rte.c
lemma12_1_rte.c
lemma12_2_rte.c
lemma12_3_rte.c
lemma12_4_rte.c
lemma12_5_rte.c
lemma12_6_rte.c
lemma2f_rte.c
lemma2f_1_rte.c
lemma2f_2_rte.c
lemma2f_3_rte.c
lemma2f_4_rte.c
lemma_all_star_A_rte.c
lemma_all_star_A_1_rte.c
lemma_all_star_A_10_rte.c
lemma_all_star_A_11_rte.c
lemma_all_star_A_12_rte.c
lemma_all_star_A_2_rte.c
lemma_all_star_A_3_rte.c
lemma_all_star_A_4_rte.c
lemma_all_star_A_5_rte.c
lemma_all_star_A_6_rte.c
lemma_all_star_A_7_rte.c
lemma_all_star_A_8_rte.c
lemma_all_star_A_9_rte.c
lemma_star_A_rte.c
lemma_star_A_1_rte.c
lemma_star_A_2_rte.c
lemma_star_A_3_rte.c
lemma_star_A_4_rte.c
lemma_star_A_5_rte.c
lemma_star_A_6_rte.c
lemma_star_A_7_rte.c
lemma_star_A_8_rte.c
lemma_star_A_all_rte.c
lemma_star_A_all_1_rte.c
lemma_star_A_all_10_rte.c
lemma_star_A_all_11_rte.c
lemma_star_A_all_12_rte.c
lemma_star_A_all_13_rte.c
lemma_star_A_all_14_rte.c
lemma_star_A_all_2_rte.c
lemma_star_A_all_3_rte.c
lemma_star_A_all_4_rte.c
lemma_star_A_all_5_rte.c
lemma_star_A_all_6_rte.c
lemma_star_A_all_7_rte.c
lemma_star_A_all_8_rte.c
lemma_star_A_all_9_rte.c
lemma_star_A_dec_rte.c
lemma_star_A_dec_1_rte.c
lemma_star_A_dec_2_rte.c
lemma_star_A_dec_3_rte.c
lemma_star_A_dec_4_rte.c
lemma_star_A_dec_5_rte.c
lemma_star_A_dec_6_rte.c
lemma_star_A_dec_7_rte.c
lemma_star_A_dec_8_rte.c
lemma_star_A_not_rte.c
lemma_star_A_not_1_rte.c
lemma_star_A_not_10_rte.c
lemma_star_A_not_2_rte.c
lemma_star_A_not_3_rte.c
lemma_star_A_not_4_rte.c
lemma_star_A_not_5_rte.c
lemma_star_A_not_6_rte.c
lemma_star_A_not_7_rte.c
lemma_star_A_not_8_rte.c
lemma_star_A_not_9_rte.c
m_aapb_rte.c
m_aapb_1_rte.c
m_aapb_2_rte.c
m_aapb_3_rte.c
m_aapb_4_rte.c
main_rte.c
main_1_rte.c
main_2_rte.c
main_3_rte.c
main_4_rte.c
matcher_rte.c
matcher_1_rte.c
matcher_2_rte.c
matcher_a_or_b_rte.c
matcher_a_or_b_1_rte.c
matcher_a_or_b_2_rte.c
matcher_ab_rte.c
matcher_ab_1_rte.c
matcher_ab_2_rte.c
max2_rte.c
max2_1_rte.c
max2_2_rte.c
max_idx_rte.c
max_idx_1_rte.c
max_idx_2_rte.c
max_ptr_rte.c
max_ptr_1_rte.c
max_ptr_2_rte.c
max_ptr_3_rte.c
max_ptr_4_rte.c
max_ptr_5_rte.c
max_seq_rte.c
max_seq_1_rte.c
max_seq_2_rte.c
maxarray_rte.c
maxarray_1_rte.c
maxarray_2_rte.c
min_rte.c
min_1_rte.c
min_2_rte.c
min_3_rte.c
min_4_rte.c
min_5_rte.c
minus1_rte.c
minus1_1_rte.c
opa_rte.c
opa_1_rte.c
opa_2_rte.c
opb_rte.c
opc_rte.c
partition_rte.c
partition_1_rte.c
partition_2_rte.c
pick_element_rte.c
pick_element_1_rte.c
pick_element_2_rte.c
pick_element_3_rte.c
pick_first_rte.c
pick_first_1_rte.c
pick_first_2_rte.c
pick_first_3_rte.c
pick_index_rte.c
pick_index_1_rte.c
pick_index_2_rte.c
pick_index_3_rte.c
pick_index_4_rte.c
pick_index_5_rte.c
predicate_rte.c
predicate_1_rte.c
predicate_2_rte.c
q2_rte.c
q2_1_rte.c
q2_2_rte.c
reverse_rte.c
reverse_1_rte.c
reverse_2_rte.c
swap_rte.c
swap_1_rte.c
swap_2_rte.c
swap_3_rte.c
swap_4_rte.c
swap_5_rte.c
while_rte.c
while_1_rte.c
while_2_rte.c
while_3_rte.c
while_4_rte.c
wrapLines_rte.c
wrapLines_simpl_rte.c
)

for file in "${files[@]}"; do
    output="./output_cvc5_tests/output_${file%_rte.c}_cvc5.txt"
    echo "Processing $file ..."
    frama-c -wp -wp-prover cvc5 "$file" > "$output"
done

