/* Generated by Frama-C */
#include "stddef.h"
#include "string.h"
int dfa(char *x0)
{
  int x89;
  int x93;
  int x2 = 1;
  int x3 = 0;
  char *x5 = x0;
  while (1) {
    int x13;
    char *x7 = x5;
    /*@ assert rte: mem_access: \valid_read(x7 + 0); */
    char x8 = *(x7 + 0);
    int x9 = (int)x8 == '\000';
    if (x9) x13 = 0;
    else {
      int x11 = x2;
      x13 = x11;
    }
    if (! x13) break;
    char *x37 = x5;
    char *x38 = x37 + 1;
    x5 = x38;
  }
  char *x84 = x5;
  /*@ assert rte: mem_access: \valid_read(x84 + 0); */
  char x85 = *(x84 + 0);
  int x86 = (int)x85 == '\000';
  if (x86) {
    int x87 = x2;
    x89 = x87;
  }
  else x89 = 0;
  if (x89) {
    int x90 = x3;
    int x91 = x90 == 2;
    x93 = x91;
  }
  else x93 = 0;
  return x93;
}


