/* Generated by Frama-C */
int distance(int a, int b)
{
  int __retres;
  if (a < b) {
    /*@ assert rte: signed_overflow: -2147483648 ≤ b - a; */
    /*@ assert rte: signed_overflow: b - a ≤ 2147483647; */
    __retres = b - a;
    goto return_label;
  }
  else {
    /*@ assert rte: signed_overflow: -2147483648 ≤ a - b; */
    /*@ assert rte: signed_overflow: a - b ≤ 2147483647; */
    __retres = a - b;
    goto return_label;
  }
  return_label: return __retres;
}


