/* Generated by Frama-C */
char e(int i)
{
  char __retres;
  int tmp;
  if (0 <= i) 
    if (i <= 9) 
      /*@ assert rte: signed_overflow: i + (int)'0' ≤ 2147483647; */
      tmp = i + '0';
    else tmp = ' ';
  else tmp = ' ';
  __retres = (char)tmp;
  return __retres;
}


