/* Generated by Frama-C */
extern int ( /* missing proto */ e)(int x_0);

extern int ( /* missing proto */ d)(int x_0);

char ed(char c)
{
  char __retres;
  int tmp_0;
  int tmp;
  tmp = d((int)c);
  tmp_0 = e(tmp);
  __retres = (char)tmp_0;
  return __retres;
}


