/* Generated by Frama-C */
extern int ( /* missing proto */ e)(int x_0);

extern int ( /* missing proto */ d)(int x_0);

char ede(int i)
{
  char __retres;
  int tmp_1;
  int tmp_0;
  int tmp;
  tmp = e(i);
  tmp_0 = d(tmp);
  tmp_1 = e(tmp_0);
  __retres = (char)tmp_1;
  return __retres;
}


