/* Generated by Frama-C */
int eq_vec_Int(int *x16, int x17, int *x18, int x19)
{
  int x33;
  int x21 = x17 == x19;
  if (x21) {
    int x32 = 1;
    {
      int x24 = 0;
      while (x24 < x17) {
        {
          /*@ assert rte: mem_access: \valid_read(x16 + x24); */
          int x29 = *(x16 + x24);
          /*@ assert rte: mem_access: \valid_read(x18 + x24); */
          int x30 = *(x18 + x24);
          int x31 = x29 == x30;
          if (! x31) {
            x32 = 0;
            break;
          }
        }
        /*@ assert rte: signed_overflow: x24 + 1 ≤ 2147483647; */
        x24 ++;
      }
    }
    x33 = x32;
  }
  else x33 = 0;
  return x33;
}


