/* Generated by Frama-C */
int index(int x0, int x1, int x2, int x3)
{
  /*@ assert rte: signed_overflow: -2147483648 ≤ x2 * x1; */
  /*@ assert rte: signed_overflow: x2 * x1 ≤ 2147483647; */
  int x5 = x2 * x1;
  /*@ assert rte: signed_overflow: -2147483648 ≤ x5 + x3; */
  /*@ assert rte: signed_overflow: x5 + x3 ≤ 2147483647; */
  int x6 = x5 + x3;
  return x6;
}

void add(int *x63, int x64, int x65, int *x66, int x67, int x68, int *x69,
         int x70, int x71)
{
  int x76 = 0;
  while (x76 < x70) {
    {
      int x78 = 0;
      while (x78 < x71) {
        {
          int tmp_1;
          int x79 = index(x64,x65,x76,x78);
          /*@ assert rte: mem_access: \valid_read(x63 + x79); */
          int x80 = *(x63 + x79);
          int x81 = index(x67,x68,x76,x78);
          /*@ assert rte: mem_access: \valid_read(x66 + x81); */
          int x82 = *(x66 + x81);
          if (x80) tmp_1 = 1;
          else 
            if (x82) tmp_1 = 1; else tmp_1 = 0;
          int x83 = tmp_1;
          int x84 = index(x70,x71,x76,x78);
          /*@ assert rte: mem_access: \valid(x69 + x84); */
          *(x69 + x84) = x83;
        }
        /*@ assert rte: signed_overflow: x78 + 1 ≤ 2147483647; */
        x78 ++;
      }
    }
    /*@ assert rte: signed_overflow: x76 + 1 ≤ 2147483647; */
    x76 ++;
  }
  return;
}

void scalar_mult(int x110, int *x111, int x112, int x113, int *x114,
                 int x115, int x116)
{
  int x121 = 0;
  while (x121 < x115) {
    {
      int x123 = 0;
      while (x123 < x116) {
        {
          int x126;
          if (x110) {
            int x124 = index(x112,x113,x121,x123);
            /*@ assert rte: mem_access: \valid_read(x111 + x124); */
            int x125 = *(x111 + x124);
            x126 = x125;
          }
          else x126 = 0;
          int x127 = index(x115,x116,x121,x123);
          /*@ assert rte: mem_access: \valid(x114 + x127); */
          *(x114 + x127) = x126;
        }
        /*@ assert rte: signed_overflow: x123 + 1 ≤ 2147483647; */
        x123 ++;
      }
    }
    /*@ assert rte: signed_overflow: x121 + 1 ≤ 2147483647; */
    x121 ++;
  }
  return;
}


