/* Generated by Frama-C */
int index(int x0, int x1, int x2, int x3)
{
  /*@ assert rte: signed_overflow: -2147483648 ≤ x2 * x1; */
  /*@ assert rte: signed_overflow: x2 * x1 ≤ 2147483647; */
  int x5 = x2 * x1;
  /*@ assert rte: signed_overflow: -2147483648 ≤ x5 + x3; */
  /*@ assert rte: signed_overflow: x5 + x3 ≤ 2147483647; */
  int x6 = x5 + x3;
  return x6;
}


