/* Generated by Frama-C */
extern int ( /* missing proto */ predicate)(int x_0);

int index_where(int *v, int n, int *o)
{
  int r = 0;
  {
    int i = 0;
    while (i < n) {
      {
        int tmp_0;
        /*@ assert rte: mem_access: \valid_read(v + i); */
        tmp_0 = predicate(*(v + i));
        if (tmp_0) {
          int tmp;
          tmp = r;
          /*@ assert rte: signed_overflow: r + 1 ≤ 2147483647; */
          r ++;
          /*@ assert rte: mem_access: \valid(o + tmp); */
          *(o + tmp) = i;
        }
      }
      /*@ assert rte: signed_overflow: i + 1 ≤ 2147483647; */
      i ++;
    }
  }
  return r;
}


