/* Generated by Frama-C */
void inswap(int *x0, int x1, int x2)
{
  /*@ assert rte: mem_access: \valid_read(x0 + x1); */
  int x4 = *(x0 + x1);
  /*@ assert rte: mem_access: \valid_read(x0 + x2); */
  int x5 = *(x0 + x2);
  /*@ assert rte: mem_access: \valid(x0 + x1); */
  *(x0 + x1) = x5;
  /*@ assert rte: mem_access: \valid(x0 + x2); */
  *(x0 + x2) = x4;
  return;
}


