/* Generated by Frama-C */
extern int ( /* missing proto */ swap)(int *x_0, int *x_1);

int main(void)
{
  int __retres;
  int a = 13;
  int b = 14;
  swap(& a,& b);
  __retres = 0;
  return __retres;
}


