/* Generated by Frama-C */
#include "stddef.h"
#include "string.h"
int matcher(char *x0)
{
  size_t tmp;
  int x6;
  int x7;
  tmp = strlen((char const *)x0);
  int x2 = (int)tmp;
  int x3 = 0 < x2;
  if (x3) {
    /*@ assert rte: mem_access: \valid_read(x0 + 0); */
    char x4 = *(x0 + 0);
    int x5 = 'a' == (int)x4;
    x6 = x5;
  }
  else x6 = 0;
  if (x6) x7 = 1; else x7 = 0;
  return x7;
}


