/* Generated by Frama-C */
extern int ( /* missing proto */ strlen)(char *x_0);

int matcher(char *x0)
{
  int x6;
  int x7;
  int x2 = strlen(x0);
  int x3 = 0 < x2;
  if (x3) {
    /*@ assert rte: mem_access: \valid_read(x0 + 0); */
    char x4 = *(x0 + 0);
    int x5 = 'a' == (int)x4;
    x6 = x5;
  }
  else x6 = 0;
  if (x6) x7 = 1; else x7 = 0;
  return x7;
}


