/* Generated by Frama-C */
int max_ptr(int *a, int *b)
{
  int tmp;
  /*@ assert rte: mem_access: \valid_read(a); */
  /*@ assert rte: mem_access: \valid_read(b); */
  if (*a > *b) 
    /*@ assert rte: mem_access: \valid_read(a); */
    tmp = *a;
  else 
    /*@ assert rte: mem_access: \valid_read(b); */
    tmp = *b;
  return tmp;
}


