/* Generated by Frama-C */
void max_ptr(int *p, int *q)
{
  /*@ assert rte: mem_access: \valid_read(p); */
  /*@ assert rte: mem_access: \valid_read(q); */
  if (*p > *q) {
    /*@ assert rte: mem_access: \valid_read(p); */
    int tmp = *p;
    /*@ assert rte: mem_access: \valid(p); */
    /*@ assert rte: mem_access: \valid_read(q); */
    *p = *q;
    /*@ assert rte: mem_access: \valid(q); */
    *q = tmp;
  }
  return;
}


