/* Generated by Frama-C */
int max_idx(unsigned int *t, int len)
{
  int max = 0;
  {
    int i = 1;
    while (i < len) {
      /*@ assert rte: mem_access: \valid_read(t + max); */
      /*@ assert rte: mem_access: \valid_read(t + i); */
      if (*(t + max) < *(t + i)) max = i;
      /*@ assert rte: signed_overflow: i + 1 ≤ 2147483647; */
      i ++;
    }
  }
  return max;
}


