/* Generated by Frama-C */
extern int ( /* missing proto */ max_idx)(unsigned int *x_0, int x_1);

int max_seq(unsigned int *t, int len)
{
  int __retres;
  int tmp;
  if (len <= 0) {
    __retres = -1;
    goto return_label;
  }
  tmp = max_idx(t,len);
  ;
  /*@ assert rte: mem_access: \valid_read(t + tmp); */
  __retres = (int)*(t + tmp);
  return_label: return __retres;
}


