/* Generated by Frama-C */
int min(int a, int b)
{
  int __retres;
  if (a < b) {
    __retres = a;
    goto return_label;
  }
  else {
    __retres = b;
    goto return_label;
  }
  return_label: return __retres;
}


