/* Generated by Frama-C */
void q2(int *a, int n, int k)
{
  int j = 0;
  while (j < k) {
    /*@ assert rte: mem_access: \valid_read(a + j); */
    /*@ assert rte: signed_overflow: j + 1 ≤ 2147483647; */
    /*@ assert rte: mem_access: \valid_read(a + (int)(j + 1)); */
    if (*(a + j) > *(a + (j + 1))) {
      /*@ assert rte: mem_access: \valid_read(a + j); */
      int t = *(a + j);
      /*@ assert rte: mem_access: \valid(a + j); */
      /*@ assert rte: signed_overflow: j + 1 ≤ 2147483647; */
      /*@ assert rte: mem_access: \valid_read(a + (int)(j + 1)); */
      *(a + j) = *(a + (j + 1));
      /*@ assert rte: mem_access: \valid(a + (int)(j + 1)); */
      /*@ assert rte: signed_overflow: j + 1 ≤ 2147483647; */
      *(a + (j + 1)) = t;
    }
    /*@ assert rte: signed_overflow: j + 1 ≤ 2147483647; */
    j ++;
  }
  return;
}


