/* Generated by Frama-C */
void reverse(int *a, int *res, int size)
{
  int i;
  /*@ assert rte: signed_overflow: -2147483648 ≤ size - 1; */
  i = size - 1;
  while (i >= 0) {
    /*@ assert rte: mem_access: \valid(res + i); */
    /*@ assert rte: signed_overflow: -2147483648 ≤ size - i; */
    /*@ assert rte: signed_overflow: size - i ≤ 2147483647; */
    /*@ assert rte: signed_overflow: -2147483648 ≤ (int)(size - i) - 1; */
    /*@ assert rte: mem_access: \valid_read(a + (int)((int)(size - i) - 1));
    */
    *(res + i) = *(a + ((size - i) - 1));
    /*@ assert rte: signed_overflow: -2147483648 ≤ i - 1; */
    i --;
  }
  return;
}


