import re
import os
import pandas as pd
import matplotlib.pyplot as plt

# ============================================================
# CONFIGURATION
# ============================================================
LOG_FILE = "output_eva_log_updated.txt"
OUTPUT_DIR = "figures"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ============================================================
# STEP 1: Load EVA log
# ============================================================
with open(LOG_FILE, "r", encoding="utf-8", errors="ignore") as f:
    text = f.read()

# ============================================================
# STEP 2: Split log into per-file analysis blocks
# ============================================================
blocks = re.split(r"\n\s*Analyzing\s+", text)

records = []

for block in blocks:
    file_match = re.match(r"([A-Za-z0-9_\-]+\.c)", block)
    if not file_match:
        continue

    file_name = file_match.group(1)

    record = {
        "file": file_name,
        "functions_analyzed": None,
        "function_coverage": None,
        "statements_reached": None,
        "statements_total": None,
        "stmt_coverage": None,
        "alarms": 0,
        "kernel_warnings": 0,
        "analysis_successful": True
    }

    # --------------------------------------------------------
    # Detect failed analysis
    # --------------------------------------------------------
    if "Analysis failed" in block or "Frama-C aborted" in block:
        record["analysis_successful"] = False
        records.append(record)
        continue

    # --------------------------------------------------------
    # Functions analyzed
    # Example:
    # 2 functions analyzed (out of 2): 100% coverage.
    # --------------------------------------------------------
    m = re.search(
        r"(\d+)\s+functions analyzed.*?:\s*(\d+)% coverage",
        block
    )
    if m:
        record["functions_analyzed"] = int(m.group(1))
        record["function_coverage"] = int(m.group(2))

    # --------------------------------------------------------
    # Statements coverage
    # Example:
    # 7 statements reached (out of 7): 100% coverage.
    # --------------------------------------------------------
    m = re.search(
        r"(\d+)\s+statements reached\s+\(out of\s+(\d+)\):\s*(\d+)% coverage",
        block
    )
    if m:
        record["statements_reached"] = int(m.group(1))
        record["statements_total"] = int(m.group(2))
        record["stmt_coverage"] = int(m.group(3))

    # --------------------------------------------------------
    # Alarms
    # Example:
    # 0 alarms generated by the analysis.
    # --------------------------------------------------------
    m = re.search(r"(\d+)\s+alarms generated", block)
    if m:
        record["alarms"] = int(m.group(1))

    # --------------------------------------------------------
    # Kernel warnings
    # Example:
    # by the Frama-C kernel:    0 errors    2 warnings
    # --------------------------------------------------------
    m = re.search(
        r"Frama-C kernel:\s+\d+\s+errors\s+(\d+)\s+warnings",
        block
    )
    if m:
        record["kernel_warnings"] = int(m.group(1))

    records.append(record)

df = pd.DataFrame(records)

# ============================================================
# STEP 3: Split successful vs failed analyses
# ============================================================
df_success = df[df["analysis_successful"]]
df_failed = df[~df["analysis_successful"]]

# ============================================================
# STEP 4: Summary statistics (paper-ready)
# ============================================================
def summarize(subset, name):
    return {
        "Dataset": name,
        "Files": len(subset),
        "Mean coverage (%)": subset["stmt_coverage"].mean(),
        "Median coverage (%)": subset["stmt_coverage"].median(),
        "Mean alarms": subset["alarms"].mean(),
        "Max alarms": subset["alarms"].max(),
        "Files with kernel warnings": (subset["kernel_warnings"] > 0).sum(),
    }

summary_df = pd.DataFrame([
    summarize(df, "All files"),
    summarize(df_success, "Successful"),
    summarize(df_failed, "Failed"),
])

print("\n===== EVA SUMMARY (SUCCESS VS FAILED) =====\n")
print(summary_df.to_string(index=False))

# ============================================================
# STEP 5: Global plotting style (publishable)
# ============================================================
plt.rcParams.update({
    "font.size": 12,
    "axes.titlesize": 14,
    "axes.labelsize": 12,
    "figure.figsize": (6, 4),
    "axes.grid": True,
    "grid.alpha": 0.3,
})

# ============================================================
# STEP 6: Histogram – Statement Coverage
# ============================================================
plt.figure()
plt.hist(
    df_success["stmt_coverage"].dropna(),
    bins=20, alpha=0.7, label="Successful"
)
plt.hist(
    df_failed["stmt_coverage"].dropna(),
    bins=20, alpha=0.7, label="Failed"
)

plt.xlabel("Statement Coverage (%)")
plt.ylabel("Number of Files")
plt.title("Distribution of Statement Coverage")
plt.legend()
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/coverage_histogram.png", dpi=300)
plt.close()

# ============================================================
# STEP 7: Histogram – Alarms per File
# ============================================================
plt.figure()
plt.hist(
    df["alarms"],
    bins=range(0, int(df["alarms"].max()) + 2),
    align="left",
    rwidth=0.8
)

plt.xlabel("Number of Alarms")
plt.ylabel("Number of Files")
plt.title("Distribution of EVA Alarms per File")
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/alarms_histogram.png", dpi=300)
plt.close()

# ============================================================
# STEP 8: Scatter – Coverage vs Kernel Warnings
# ============================================================
plt.figure()
plt.scatter(
    df["kernel_warnings"],
    df["stmt_coverage"],
    alpha=0.6
)

plt.xlabel("Frama-C Kernel Warnings")
plt.ylabel("Statement Coverage (%)")
plt.title("Coverage vs Kernel Warnings")
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/coverage_vs_warnings.png", dpi=300)
plt.close()

# ============================================================
# STEP 9: Analysis outcome (success vs failed)
# ============================================================
success_rate = df["analysis_successful"].mean() * 100

plt.figure(figsize=(4, 4))
plt.bar(
    ["Successful", "Failed"],
    [success_rate, 100 - success_rate]
)

plt.ylabel("Percentage of Files (%)")
plt.title("EVA Analysis Outcome")
plt.tight_layout()
plt.savefig(f"{OUTPUT_DIR}/analysis_outcome.png", dpi=300)
plt.close()

print(f"\nAll figures saved in: {OUTPUT_DIR}")

